# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\dev\public\python38\Mafia42\searchuser\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 680)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Joo/Documents/joo/main/지나/지나당근.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchbtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchbtn.setGeometry(QtCore.QRect(200, 620, 101, 31))
        self.searchbtn.setObjectName("searchbtn")
        self.console = QtWidgets.QTextBrowser(self.centralwidget)
        self.console.setGeometry(QtCore.QRect(10, 10, 481, 491))
        self.console.setObjectName("console")
        self.idinput = QtWidgets.QLineEdit(self.centralwidget)
        self.idinput.setGeometry(QtCore.QRect(140, 520, 291, 31))
        self.idinput.setObjectName("idinput")
        self.nickinput = QtWidgets.QLineEdit(self.centralwidget)
        self.nickinput.setGeometry(QtCore.QRect(140, 570, 291, 31))
        self.nickinput.setObjectName("nickinput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 520, 51, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 570, 101, 31))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mafia42 User Search Client"))
        self.searchbtn.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Input ID"))
        self.label_2.setText(_translate("MainWindow", "Input Nickname"))
